---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: cattle-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: rancher
      sourceRef:
        kind: HelmRepository
        name: rancher-stable
  values:
    hostname: rancher.hostbaitor.com
    ingress:
      tls:
        source: letsEncrypt
    letsEncrypt:
      email: jakdept@gmail.com
