---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-vip
  namespace: kube-system
spec:
  interval: 10m0s
  chart:
    spec:
      chart: kube-vip
      sourceRef:
        kind: HelmRepository
        name: kube-vip
  values:
    config:
      vip_interface: eth0
      vip_address: "209.59.172.36/32"