---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: rancher-stable
  namespace: cattle-system
spec:
  interval: 1m0s
  url: https://releases.rancher.com/server-charts/stable

